all:
	time ./generate-experiments-for-MemSafety-Array.sh

clean:
	rm -rf MemSafety-Arrays
	rm -rf run_experiment-MemSafety-Arrays-Log-*
	rm -rf MemSafety-Arrays-temp-array-examples.sh
	rm -rf MemSafety-Arrays-temp-array-memsafety-realloc.sh
	rm -rf MemSafety-Arrays-temp-array-memsafety.sh
	rm -rf run_experiment-MemSafety-Arrays-Log-array-memsafety.txt
